{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kublai.secretName" . }}
  namespace: {{ include "kublai.namespace" . }}
  labels:
{{ include "kublai.labels" . | indent 4 }}
type: Opaque
stringData:
{{- range $key, $value := .Values.secretConfig }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
