apiVersion: v1
kind: Service
metadata:
  name: {{ include "kublai.fullname" . }}-api
  namespace: {{ include "kublai.namespace" . }}
  labels:
{{ include "kublai.labels" . | indent 4 }}
spec:
  selector:
    app.kubernetes.io/name: kublai-api
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.api.service.port }}
      targetPort: http
