{{- if .Values.api.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "artifortress.fullname" . }}-api
  namespace: {{ include "artifortress.namespace" . }}
  labels:
{{ include "artifortress.labels" . | indent 4 }}
spec:
  minAvailable: {{ .Values.api.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: artifortress-api
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
