apiVersion: v1
kind: Secret
metadata:
  name: {{ include "artifortress.fullname" . }}-secrets
  namespace: {{ include "artifortress.namespace" . }}
  labels:
{{ include "artifortress.labels" . | indent 4 }}
type: Opaque
stringData:
{{- range $key, $value := .Values.secretConfig }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
