apiVersion: v1
kind: Service
metadata:
  name: {{ include "artifortress.fullname" . }}-api
  namespace: {{ include "artifortress.namespace" . }}
  labels:
{{ include "artifortress.labels" . | indent 4 }}
spec:
  selector:
    app.kubernetes.io/name: artifortress-api
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.api.service.port }}
      targetPort: http
