apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kublai
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 512m
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - kublai.example.com
      secretName: kublai-tls
  rules:
    - host: kublai.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kublai-api
                port:
                  name: http
